# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ana_sayfa.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Anasayfa(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(685, 399)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 651, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.leKitapara = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.leKitapara.setObjectName("leKitapara")
        self.horizontalLayout.addWidget(self.leKitapara)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 330, 651, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnEkle = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btnEkle.setObjectName("btnEkle")
        self.horizontalLayout_2.addWidget(self.btnEkle)
        self.btnDuzenle = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btnDuzenle.setObjectName("btnDuzenle")
        self.horizontalLayout_2.addWidget(self.btnDuzenle)
        self.btnSil = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btnSil.setObjectName("btnSil")
        self.horizontalLayout_2.addWidget(self.btnSil)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 280, 651, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnonceki = QtWidgets.QToolButton(self.horizontalLayoutWidget_3)
        self.btnonceki.setArrowType(QtCore.Qt.LeftArrow)
        self.btnonceki.setObjectName("btnonceki")
        self.horizontalLayout_3.addWidget(self.btnonceki)
        self.btnsonraki = QtWidgets.QToolButton(self.horizontalLayoutWidget_3)
        self.btnsonraki.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnsonraki.setArrowType(QtCore.Qt.RightArrow)
        self.btnsonraki.setObjectName("btnsonraki")
        self.horizontalLayout_3.addWidget(self.btnsonraki)
        self.progressBar = QtWidgets.QProgressBar(self.horizontalLayoutWidget_3)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_3.addWidget(self.progressBar)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(20, 60, 651, 211))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Kitap Adı:"))
        self.leKitapara.setPlaceholderText(_translate("Dialog", "Aramak istediğiniz kitap"))
        self.btnEkle.setText(_translate("Dialog", "EKLE"))
        self.btnDuzenle.setText(_translate("Dialog", "DÜZENLE"))
        self.btnSil.setText(_translate("Dialog", "SİL"))
        self.btnonceki.setText(_translate("Dialog", "..."))
        self.btnsonraki.setText(_translate("Dialog", "..."))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Kitap Adı"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Yazar"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Tür"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Basım Yılı"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Anasayfa()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
