# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'emanet.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Emanet(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(719, 244)
        self.leUyeAd = QtWidgets.QLineEdit(Dialog)
        self.leUyeAd.setGeometry(QtCore.QRect(100, 30, 221, 22))
        self.leUyeAd.setObjectName("leUyeAd")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 30, 55, 21))
        self.label.setObjectName("label")
        self.dateVerilis = QtWidgets.QDateEdit(Dialog)
        self.dateVerilis.setGeometry(QtCore.QRect(120, 60, 91, 31))
        self.dateVerilis.setObjectName("dateVerilis")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 81, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 81, 31))
        self.label_3.setObjectName("label_3")
        self.dateTeslim = QtWidgets.QDateEdit(Dialog)
        self.dateTeslim.setGeometry(QtCore.QRect(120, 100, 91, 31))
        self.dateTeslim.setObjectName("dateTeslim")
        self.btniptal = QtWidgets.QPushButton(Dialog)
        self.btniptal.setGeometry(QtCore.QRect(30, 160, 93, 28))
        self.btniptal.setObjectName("btniptal")
        self.btnKaydet = QtWidgets.QPushButton(Dialog)
        self.btnKaydet.setGeometry(QtCore.QRect(140, 160, 93, 28))
        self.btnKaydet.setObjectName("btnKaydet")
        self.leSecim = QtWidgets.QLineEdit(Dialog)
        self.leSecim.setGeometry(QtCore.QRect(380, 30, 231, 22))
        self.leSecim.setObjectName("leSecim")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Üye Adı"))
        self.label_2.setText(_translate("Dialog", "Veriliş Tarihi"))
        self.label_3.setText(_translate("Dialog", "Teslim Tarihi"))
        self.btniptal.setText(_translate("Dialog", "İPTAL"))
        self.btnKaydet.setText(_translate("Dialog", "KAYDET"))
        self.leSecim.setPlaceholderText(_translate("Dialog", "Kitap Adı"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Emanet()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
